name: Deploy to Server

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: '140.238.8.114'
          username: 'stmlymc'
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # Navigate to the project directory
            cd ADT
            # Pull latest changes
            git pull origin main
            # Install dependencies
            npm install
            # Restart application
            pm2 reload all