name: Deploy to Server

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # 서버에서 실행할 명령어들
            cd /home/ubuntu/my-project  # 프로젝트 폴더로 이동
            git pull origin main        # 최신 코드 받기
            npm install                 # 의존성 설치 (필요시)
            npm run build               # 빌드 (필요시)
            pm2 reload all              # 서버 재시작 (예: PM2 사용시)