host : aws-1-ap-south-1.pooler.supabase.com
port : 6543
database : postgres
timezone : Asia/Seoul   
user : postgres.dceyudsvscmoefglvxkn
password : Spacebankdev5%


CREATE TABLE public.test (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT test_pkey PRIMARY KEY (id)
);